spring:
  application:
    name: commerce-payment
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: payment_user
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080

# JWT 설정
jwt:
  secret: "c3BhcnRhLXBheW1lbnQtand0LXNlY3JldC1rZXktZm9yLWJvb3RjYW1wLTIwMjYtdmVyeS1sb25nLXNlY3JldA=="  # Base64 encoded
  expiration: 3600000  # 1시간 (ms)
  
portone:
  base-url: "https://api.portone.io"
  api-secret: "kwjfvYDdq35AIOKiqtX81g36AHgGowto4Af3YGwruD8BPpBvAmB3qoHePuGZlPohtJw1IjJJdIjKjzHW"
  store-id: "store-6c5d3170-6080-4f70-aa96-1f2baf8d349a"
  channel-key: "channel-key-d45e37ea-9034-495a-b691-c223dbf16f12"